server:
  port: 8081
spring:
  application:
    name: service-product
  sleuth:
    sampler:
      probability: 1.0  #采样百分比
  zipkin:
    base-url: http://127.0.0.1:9411/  #zipkin server的请求地址
    discovery-client-enabled: false #让nacos把它当成一个URL，而不要当做资源名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.229.68.228:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
